# .github/workflows/app.yaml
name: dbt slim ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  dbt-test:
    runs-on: [ self-hosted, linux, abstractions ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: DBT compile to create manifest to compare to
        working-directory: ./spellbook
        run: "pipenv run dbt compile"

      # Install dependencies
      - name: DBT seed
        working-directory: ./spellbook
        run: "pipenv run dbt deps"

      # Use build in to run and test at same time
      - name: DBT build
        working-directory: ./spellbook
        run: "pipenv run dbt build --select  +tag:integration_test"

        # Run a second time to check for conflicts or issues overwriting
      - name: DBT build
        working-directory: ./spellbook
        run: "pipenv run dbt build --select  +tag:integration_test"
