# .github/workflows/app.yaml
name: dbt slim ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  dbt-test:
    runs-on: [ self-hosted, linux, abstractions ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Fetch latest run_id
        env:
          URL: 'https://cloud.getdbt.com/api/v2/accounts/58579/runs/?job_definition_id=81672&order_by=-finished_at&limit=2'
        run : |
          GITHUB_ENV=$(curl -s --header '@/root/.headers' $URL | jq .data[1].id)
      - name: Fetch latest manifest.json
        env:
          URL: 'https://cloud.getdbt.com/api/v2/accounts/58579/runs/62469111/artifacts/manifest.json'
        run: |
          curl -s -o spellbook/manifest.json --url $URL -header '@/root/.headers'
      - name: dbt compile to create manifest to compare to
        working-directory: ./spellbook
        run: "dbt compile"

      - name: DBT seed
        working-directory: ./spellbook
        run: "dbt seed --select state:modified --state ."

      - name: DBT run
        working-directory: ./spellbook
        run: "dbt run --select state:modified --state ."

      - name: DBT test
        working-directory: ./spellbook
        run: "dbt test --select state:new state:modified --state ."