# .github/workflows/app.yaml
name: dbt slim ci

on:
  pull_request:
  workflow_distpach:
  push:
    branches:
      - 'main'

jobs:
  dbt-test:
    runs-on: [ self-hosted, linux, abstractions ]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Get latest manifest
        working-directory: ./spellbook
        run: "pipenv run python fetch_latest_manifest.py --dbt_api_token $(curl -s --header '@/root/.headers' $URL | jq .data[1].id)"

      - name: dbt compile to create manifest to compare to
        working-directory: ./spellbook
        run: "dbt compile"

      - name: DBT seed
        working-directory: ./spellbook
        run: "dbt seed --select state:modified --state ."

      - name: DBT run
        working-directory: ./spellbook
        run: "dbt run --select state:modified --state ."

      - name: DBT test
        working-directory: ./spellbook
        run: "dbt test --select state:new state:modified --state ."
